[package]
name = "pcw_regrs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive-new = "0.5.9"
ndarray = "0.15.6"
ordered-float = "3.7.0"
pcw_fn = "0.2.1"
thiserror = "1.0.43"
polyfit-residuals = { version = "0.6.1", features = ["parallel_rayon"] }
num-traits = "0.2.15"
